- hosts: mikrotik
  connection: network_cli
  gather_facts: false
  tasks:
  - name: Get RB info
    routeros_command:
      commands: "/environment print"
    register: system_print
  - name: debug print after
    debug: var=system_print.stdout_lines
